version: "3"
services:
  react-app:
    image: react-app-dev
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client/:/app
      - /app/node_modules

  api-server:
    image: api-server
    build: ./server/
    env_file: ./server/config/dev.env
    ports:
      - "3001:3001"
    networks:
      - mern-app
    volumes:
      - ./server/:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
